# Generated by Django 3.2 on 2022-10-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('contact', models.IntegerField()),
                ('fees', models.FloatField()),
                ('emailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=60)),
                ('photo', models.ImageField(upload_to='student_images/')),
            ],
        ),
    ]
